### ISSUE TITLE
Support for Java TrustStores 

### ISSUE THREAD

**Issue by skyfirst93** [edenhill/librd#19]
Hi I am trying to use Java truststores to connect to kafka broker. 
But the below is error is being thrown. 
```
Failed to create Admin client: Java TrustStores are not supported, use `ssl.ca.location` and a certificate file instead. See https://github.com/edenhill/librd
```
Any idea when there will a support for the same 

Using the kafka_console producer everything is working fine

**Comment by edenhill** [comment]
This repo is for librd, not librdkafka.

But, to save you the trouble of creating a new issue on librdkafka:
We will not support Java Trust or Key stores in librdkafka:
 1. it is a Java specific construct and there are tools to convert it to a more standard pfx/pkcs#12 or PEM format
 2. librdkafka supports PEM and PKCS#12, and so does the Java client.
